<?php

        //Variablen, Datentyp, Admin (1), symcon profil, name

        $DP = array(
            array("getSRN", "int", 0, "", "Seriennr."),
            array("getVER", "string", 0, "", "Firmware Version"),
            array("getTYP", "int", 0, "", "Typ"),
            array("getCNO", "string", 0, "", "Codenummer"),
            array("getMAC", "string", 0, "", "MAC Adresse"),
            array("getPRF", "int", 0, "", "eingestellte Profilnr."),
            array("getPRN", "int", 0, "", "Standardprofil"),
            array("getPN1", "string", 0, "", "Anwesend"),
            array("getPV1", "int", 0, "", ""),
            array("getPT1", "int", 0, "", ""),
            array("getPF1", "int", 0, "", ""),
            array("getPM1", "int", 0, "", ""),
            array("getPR1", "int", 0, "", ""),
            array("getPB1", "int", 0, "", ""),
            array("getPN2", "string", 0, "", "Abwesend"),
            array("getPV2", "int", 0, "", ""),
            array("getPT2", "int", 0, "", ""),
            array("getPF2", "int", 0, "", ""),
            array("getPM2", "int", 0, "", ""),
            array("getPR2", "int", 0, "", ""),
            array("getPB2", "int", 0, "", ""),
            array("getPN3", "string", 0, "", "Urlaub"),
            array("getPV3", "int", 0, "", ""),
            array("getPT3", "int", 0, "", ""),
            array("getPF3", "int", 0, "", ""),
            array("getPM3", "int", 0, "", ""),
            array("getPR3", "int", 0, "", ""),
            array("getPB3", "int", 0, "", ""),
            array("getPN4", "string", 0, "", "Erhöhter Verbrauch"),
            array("getPV4", "int", 0, "", ""),
            array("getPT4", "int", 0, "", ""),
            array("getPF4", "int", 0, "", ""),
            array("getPM4", "int", 0, "", ""),
            array("getPR4", "int", 0, "", ""),
            array("getPB4", "int", 0, "", ""),
            array("getPN5", "string", 0, "", "Maximaler Verbrauch"),
            array("getPV5", "int", 0, "", ""),
            array("getPT5", "int", 0, "", ""),
            array("getPF5", "int", 0, "", ""),
            array("getPM5", "int", 0, "", ""),
            array("getPR5", "int", 0, "", ""),
            array("getPB5", "int", 0, "", ""),
            array("getPN6", "string", 0, "", "Profil 6"),
            array("getPV6", "int", 0, "", ""),
            array("getPT6", "int", 0, "", ""),
            array("getPF6", "int", 0, "", ""),
            array("getPM6", "int", 0, "", ""),
            array("getPR6", "int", 0, "", ""),
            array("getPB6", "int", 0, "", ""),
            array("getPN7", "string", 0, "", "Profil 7"),
            array("getPV7", "int", 0, "", ""),
            array("getPT7", "int", 0, "", ""),
            array("getPF7", "int", 0, "", ""),
            array("getPM7", "int", 0, "", ""),
            array("getPR7", "int", 0, "", ""),
            array("getPB7", "int", 0, "", ""),
            array("getPN8", "string", 0, "", "Profil 8"),
            array("getPV8", "int", 0, "", ""),
            array("getPT8", "int", 0, "", ""),
            array("getPF8", "int", 0, "", ""),
            array("getPM8", "int", 0, "", ""),
            array("getPR8", "int", 0, "", ""),
            array("getPB8", "int", 0, "", ""),
            array("getTMP", "int", 0, "", ""),
            array("getVLV", "int", 0, "", ""),
            array("getCEL", "int", 0, "", ""),
            array("getBAR", "int", 0, "", ""),
            array("getNPS", "int", 1, "", ""),
            array("getALA", "string", 0, "", ""),
            array("getALM", "string", 1, "", ""),
            array("getDMA", "int", 0, "", ""),
            array("getAVO", "string", 0, "", ""),
            array("getVOL", "string", 1, "", ""),
            array("get71", "int", 1, "", ""),
            array("getBAT", "float", 0, "", ""),
            array("getNET","float",1, "", ""),
            array("getBUZ", "int", 0, "", ""),
            array("getDBD", "int", 1, "", ""),
            array("getDBT", "int", 1, "", ""),
            array("getDST", "int", 1, "", ""),
            array("getDCM", "int", 1, "", ""),
            array("getDOM", "int", 1, "", ""),
            array("getDPL", "int", 1, "", ""),
            array("getDTC", "int", 1, "", ""),
            array("getDRP", "int", 0, "", ""),
            array("getWFS", "int", 0, "", ""),
            array("getWFR", "int", 0, "", ""),
            array("getRTC", "int", 0, "", ""),
            array("getIDS", "int", 0, "", ""),
            array("getTMZ", "int", 0, "", "")
        );
